### ISSUE TITLE
Error id: -1

### ISSUE THREAD

**Issue by moe93** [loretoparisi/control-system-toolbox-for-ti89#3]
Good afternoon,

I have been trying to use the cst tool to generate the root locus. Using a simple transfer function of (s+1)/(s^2*(s+4)) yields the "Error id: -1. Data type" message.
I have set set my calculator from Exact to Auto to avoid the domain error and I have installed cst1.3.1 along with hw3patch, kerno3.1 and the lzt package all from the github repo.

Can you please help me with this error?

Thank you and kind regards.
Sincerely,

Mohammad Odeh

**Comment by RcrossF** [comment]
I have the same problem and setup on a TI-89 titanium and have not found a solution. I also noticed routh doesn't work with error -6,

**Comment by loretoparisi** [comment]
Hello the error "Data Type" seems to me to be a configuration error (maybe related to complex  radians/degree setup?)

If you have followed already all the installation steps in the CST User Guide correctly and the examples provided in the CST Reference Guide work, it could be the same error here:

https://www.quora.com/How-do-you-fix-your-TI-89-error-when-it-says-data-type-error

It could be helpful if you provide some screenshots of the errors and the step you do (screen capture done with the TI Connect app).

Hope this helps. 

> I have the same problem and setup on a TI-89 titanium and have not found a solution. I also noticed routh doesn't work with error -6,

**Comment by RcrossF** [comment]
I've been able to solve it, I did not specify a step for rlocus and was entering the list incorrectly into routh. Thank you for your help :)
