### ISSUE TITLE
pstep & gstep

### ISSUE THREAD

**Issue by gaboskar001** [loretoparisi/control-system-toolbox-for-ti89#4]
Hi
Thanks for the amazing program. Everything works exept of two step answer functions. 
When I want to execute dynamics -->step(SYS) the program does its job and i get the correct value.
After that, when i want to execute pstep(SYS), i get the error 'Error id: -6; Domain error'
Also when i try to execute Gstep(w_1(t)), i get the error: 'ERROR ;  invalid for the current mode settings'.
The exact/aprox setting of my TI-89 is on auto.
Anyone who can solve this?

**Comment by loretoparisi** [comment]
Thank you for your interest in CST for TI-89!
I will check this specific error on the TI Titanium calc.
Thanks!

**Comment by gaboskar001** [comment]
Error 'invalid for the current mode settings'
Hi 
When I follow Exaple 5 - network design 1, i get always an error when the plotting of i.e. the plotting of i.e. yr(t) starts. I get the same value for the time response as in the example but the graph doesn't seem to plot...
My setting is still on auto. Are there other settings in the calculator that I should consider? 
My CST settings are:
Time domain: continious
Display digits: float1
results:auto
angle: degree
auto: none

Sincerly

Lucas
